default_profile: cam1

profiles:
 cam1:
    yolo_model_path: "models/yolov8n-pose.pt"
    hand_model_path: "model/hand_landmarker.task"
    num_hands: 4
    input_video_paths: 
      - "/home/adeeba/Pose-Based Fighting Detector/resources/Stunt Fighting ğŸ‘ŠğŸ½.mp4"
      
    #camera_sources:
    #  - 0
    #  - "rtsp://ranu:Bharat1947@192.168.177.145:10556/stream1"
    wrist_speed_threshold: 20
    acceleration_threshold: 1000
    distance_to_neck_thresh: 50
    distance_to_face_thresh: 50
    fist_detection_radius: 20
    trajectory_dot_threshold: 0.7
    min_trigger_conditions: 4
    trigger_consistency_frames: 2
    alert_sound_path: "alert-sound-87478.mp3"
    display: true
